UBER Rich Templating Proposal (MCA)
===================================
:toc:
:numbered:

== Document Status
Author::
  Mike Amundsen, mca@amundsen.com
Status::
  *[white black-background]#Incomplete Draft#*

////
  *[white red-background]#Working Draft#*
  *[white blue-background]#Submitted to IANA#*
  *[white green-background]#Approved by IANA#*
////

Last Updated::
  {docdate}

== General
This document is a proposal for supporting "rich templating" in UBER. This proposal has the following goals:

 * Add support for additional information for describing message bodies sent from client to server.
 * Continue to support the existing +model+ pattern for cases where the additional description is not necessary.
 * Support the use of templating for both the URI and the body on the same element.
 * Continue to keep the document model for UBER very small.

== Changes to existing UBER Specifications
This document proposes a change to the way RFC6570 (URI Templates) are supported in UBER.

=== Change the +url+ Property
The +url+ property MAY contain a URI Template. Client applications MUST treat the value in +url+ properties as a URI Template (e.g. resolve any URI template values before attempting to use the value to execute a request).

.The +url+ property is a URI template
----
<uber version="1.0">
  <data rel="collection" url="http://example.org/customers" />
  <data rel="search" url="http://example.org/search?{givenname,familyname}" />
  <data rel="item" url="http://example.org/1">
    <data name="givenName">Mike</data>
    <data name="familyName">Amundsen</data>
    <data name="hatsize">Medium</data>
  </data>
  <data rel="item" url="http://example.org/2">
    <data name="givenName">Mark</data>
    <data name="familyName">Foster</data>
    <data name="hatsize">Medium</data>
  </data>
</uber>
----

=== Change the +model+ Property
The +model+ property only describes at payload (not a URL). If a client application sees a +model+ property, the client MUST use that as a guide for creating a payload. The +model+ still uses RFC570 (URI Template).

.The +model+ property is applies only to the body 
----
<!-- this UBER message... -->
<uber version="1.0">
  <data rel="item" 
      url="http://example.org/1" 
      model="{givenname,familyname,hatsize}"
      action="idempotent">
    <data name="givenName">Mike</data>
    <data name="familyName">Amundsen</data>
    <data name="hatsize">Medium</data>
  </data>
</uber>

<!-- ...translates in this HTTP request body -->
PUT HTTP/1.1
Content-Type: application/x-www-urlencoded
Content-Lengt: XXX

givenName=Mike&familyName=Amundsen&hatsize=Medium
----

== Additions to the UBER Specification
This document proposes an additional property +template+ to support rich templating of payloads.

=== Add the +template+ Element
The +template+ element is a container element that is used to identify a payload template. The +template+ element MUST have an +id+ property. The +template+ SHOULD have one or more +data+ elements. It is the +data+ elements that express the datails of the payload.

[NOTE]
====
The example shows three contraints (+required+, +options+, and +body+). See the next section for a list of proposed constraints.
====

----
<uber version="1.0">
  <template id="customerTemplate">
    <data name="familyName">
      <data name="required">true</data>
    </data>
    <data name="givenName" />
    <data name="hatSize">
      <data name="options">
        <data>Large</data>
        <data>Medium</data>
        <data>Small</data>
      </data>
    </data>
    <data name="body">
      <![CDATA[
        fname:{familyname}
        gname:{givenname}
        hsize:{hatsize}
      ]]>
    </data>
  </template>
</uber>
----

=== Add the +template+ Property
The +template+ property of the +data+ element is used to `point' to the template to use when fashioning a payload. This can be done one of two ways:

+template="http://example.org/templates/customerTemplate.xml"+::
  The +template+ property value MAY be a URL that points to an external resource.
+template="#customerTemplate"::
  the +template+ property value MAY be a fragment identifier that points to an internal +data+ element in the current representation.

==== External UBER Templates
Below is an example of an external UBER template. 

----
<!-- the template property points to... -->
<uber version="1.0">
  <data rel="item" 
      url="http://example.org/1" 
      template="http://example.org/templates/customerTemplate"
      action="idempotent">
    <data name="givenName">Mike</data>
    <data name="familyName">Amundsen</data>
    <data name="hatsize">Medium</data>
  </data>
</uber>

<!-- ... this template resource -->
<uber version="1.0">
  <data name="familyName">
    <data name="required">true</data>
  </data>
  <data name="givenName" />
  <data name="hatSize">
    <data name="options">
      <data>Large</data>
      <data>Medium</data>
      <data>Small</data>
    </data>
  </data>
</uber>
----

==== Internal UBER Templates
Below is an example of an UBER representation that contains an internal template.

----
<uber version="1.0">
  <data rel="item" 
      url="http://example.org/1" 
      template="#customerTemplate"
      action="idempotent">
    <data name="givenName">Mike</data>
    <data name="familyName">Amundsen</data>
    <data name="hatsize">Medium</data>
  </data>
  <template id="customerTemplate">
    <data name="familyName">
      <data name="required">true</data>
    </data>
    <data name="givenName" />
    <data name="hatSize">
      <data name="options">
        <data>Large</data>
        <data>Medium</data>
        <data>Small</data>
      </data>
    </data>
  </template>
</uber>
---- 

